server:
  port: 8081

spring:
  application:
    name: bootiful-greeting
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE:http://localhost:9090}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTHORIZATION_SERVICE:http://localhost:9000}/oauth2/jwks
management:
  endpoints:
    web:
      exposure:
        include: "*"