server:
  port: 8081

spring:
  application:
    name: bootiful-greeting
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE:http://localhost:9090}


management:
  endpoints:
    web:
      exposure:
        include: "*"