server:
  port: 8081

spring:
  application:
    name: bootiful-greeting
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE:http://localhost:9090}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVICE:https://localhost:9000/}issuer
management:
  endpoints:
    web:
      exposure:
        include: "*"